spring:
  profiles:
    active: "local"
  application:
    name: flight-manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1917


server:
  port: 8089
  servlet:
    context-path: /flight-manager
paht:
  entityDirectory: src/main/java/y88/kirill/flight/manager/entity
