spring:
  profiles:
    active: "local"
  application:
    name: flight-manager

---
spring:
  config:
    activate:
      on-profile: "local"
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: 1917


server:
  port: 8089
  servlet:
    context-path: /flight-manager

